"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatalogApi = void 0;
const image_1 = require("../image");
const metafield_1 = require("../metafield");
const brand_api_1 = require("./brand-api");
const category_api_1 = require("./category-api");
const category_batch_api_1 = require("./category-batch-api");
const category_tree_api_1 = require("./category-tree-api");
const product_api_1 = require("./product-api");
const product_buck_pricing_rule_api_1 = require("./product-buck-pricing-rule-api");
const product_category_assignment_api_1 = require("./product-category-assignment-api");
const product_channel_assignment_api_1 = require("./product-channel-assignment-api");
const product_complex_rule_api_1 = require("./product-complex-rule-api");
const product_custom_field_api_1 = require("./product-custom-field-api");
const product_modifier_api_1 = require("./product-modifier-api");
const product_modifier_image_api_1 = require("./product-modifier-image-api");
const product_modifier_value_api_1 = require("./product-modifier-value-api");
const product_image_api_1 = require("./product-image-api");
const product_review_api_1 = require("./product-review-api");
const product_sort_order_api_1 = require("./product-sort-order-api");
const product_variant_api_1 = require("./product-variant-api");
const product_variant_metafield_api_1 = require("./product-variant-metafield-api");
const product_variant_option_api_1 = require("./product-variant-option-api");
const product_variant_option_value_api_1 = require("./product-variant-option-value-api");
const product_video_api_1 = require("./product-video-api");
const summary_api_1 = require("./summary-api");
const variant_api_1 = require("./variant-api");
class CatalogApi {
    constructor(apiClient) {
        this.apiClient = apiClient;
        this.brandImages = new image_1.ImageApi(this.apiClient, "/v3/catalog/brands");
        this.brandMetafields = new metafield_1.MetafieldApi(this.apiClient, "/v3/catalog/brands");
        this.brands = new brand_api_1.BrandApi(this.apiClient);
        this.categoriesBatch = new category_batch_api_1.CategoryBatchApi(this.apiClient);
        this.category = new category_api_1.CategoryApi(this.apiClient);
        this.categoryMetafields = new metafield_1.MetafieldApi(this.apiClient, "/v3/catalog/categories");
        this.categoryImages = new image_1.ImageApi(this.apiClient, "/v3/catalog/categories");
        this.categoryTrees = new category_tree_api_1.CategoryTreeApi(this.apiClient);
        this.productBuckPricingRules = new product_buck_pricing_rule_api_1.ProductBuckPricingRuleApi(this.apiClient);
        this.productComplexRules = new product_complex_rule_api_1.ProductComplexRuleApi(this.apiClient);
        this.productCustomFields = new product_custom_field_api_1.ProductCustomFieldApi(this.apiClient);
        this.productMetafields = new metafield_1.MetafieldApi(this.apiClient, "/v3/catalog/products");
        this.ProductModifierImages = new product_modifier_image_api_1.ProductModifierImageApi(this.apiClient);
        this.ProductModifierValues = new product_modifier_value_api_1.ProductModifierValueApi(this.apiClient);
        this.productModifiers = new product_modifier_api_1.ProductModifierApi(this.apiClient);
        this.productImages = new product_image_api_1.ProductImageApi(this.apiClient);
        this.productReviews = new product_review_api_1.ProductReviewApi(this.apiClient);
        this.productSortOrder = new product_sort_order_api_1.ProductSortOrderApi(this.apiClient);
        this.productVariantOptionValues = new product_variant_option_value_api_1.ProductVariantOptionValueApi(this.apiClient);
        this.productVariantOptions = new product_variant_option_api_1.ProductVariantOptionApi(this.apiClient);
        this.productVariants = new product_variant_api_1.ProductVariantApi(this.apiClient);
        this.productVariantMetafields = new product_variant_metafield_api_1.ProductVariantMetafieldApi(this.apiClient);
        this.productVideos = new product_video_api_1.ProductVideoApi(this.apiClient);
        this.products = new product_api_1.ProductApi(this.apiClient);
        this.productCategoryAssignments = new product_category_assignment_api_1.ProductCategoryAssignmentApi(this.apiClient);
        this.productChannelAssignments = new product_channel_assignment_api_1.ProductChannelAssignmentApi(this.apiClient);
        this.summary = new summary_api_1.SummaryApi(this.apiClient);
        this.variants = new variant_api_1.VariantApi(this.apiClient);
    }
}
exports.CatalogApi = CatalogApi;
