import { AbandonedCartEmailsApi } from "./abandoned-cart-emails";
import { AbandonedCartApi } from "./abandoned-carts";
import { ApiClient } from "./api-client";
import { CartsApi } from "./cart";
import { CatalogApi } from "./catalog";
import { ChannelsApi } from "./channels";
import { CheckoutsApi } from "./checkouts";
import { CurrenciesApi } from "./currencies";
import { CustomTemplateAssociationsApi } from "./custom-template-associations";
import { CustomersV2Api } from "./customers-v2";
import { CustomersV3Api } from "./customers-v3";
import { EmailTemplatesApi } from "./email-templates";
import { GeographyApi } from "./geography";
import { MarketingApi } from "./marketing";
import { Config } from "./model/common";
import { OrderApi } from "./order";
import { OrderTransactionsApi } from "./order-transactions";
import { PagesApi } from "./pages";
import { PaymentMethodsApi } from "./payment-methods";
import { PaymentProcessingApi } from "./payment-processing";
import { PriceListsApi } from "./price-lists";
import { PricingApi } from "./pricing";
import { RedirectsApi } from "./redirects";
import { ScriptsApi } from "./scripts";
import { SettingsApi } from "./settings";
import { ShippingV2Api } from "./shipping-v2";
import { ShippingV3Api } from "./shipping-v3";
import { SitesApi } from "./sites";
import { StoreContentApi } from "./store-content";
import { StoreInformationApi } from "./store-information";
import { SubscribersApi } from "./subscribers";
import { SystemLogsApi } from "./system-logs";
import { TaxClassesApi } from "./tax-classes";
import { TaxPropertiesApi } from "./tax-properties";
import { TaxProviderConnectionApi } from "./tax-provider-connection";
import { TaxRatesAndZonesApi } from "./tax-rates-and-zones";
import { TaxSettingsApi } from "./tax-settings";
import { ThemesApi } from "./themes";
import { WebhooksApi } from "./webhooks";
import { WidgetsApi } from "./widgets";
import { WishlistsApi } from "./wishlists";
export declare class BigCommerceApiClient {
    private readonly config;
    readonly apiClient: ApiClient;
    readonly abandonedCarts: AbandonedCartApi;
    readonly carts: CartsApi;
    readonly catalog: CatalogApi;
    readonly channels: ChannelsApi;
    readonly checkouts: CheckoutsApi;
    readonly currencies: CurrenciesApi;
    readonly customersV2: CustomersV2Api;
    readonly customersV3: CustomersV3Api;
    readonly geography: GeographyApi;
    readonly orders: OrderApi;
    readonly orderTransactions: OrderTransactionsApi;
    readonly pricing: PricingApi;
    readonly priceLists: PriceListsApi;
    readonly redirects: RedirectsApi;
    readonly scripts: ScriptsApi;
    readonly settings: SettingsApi;
    readonly shippingV3: ShippingV3Api;
    readonly shippingV2: ShippingV2Api;
    readonly sites: SitesApi;
    readonly storeInformation: StoreInformationApi;
    readonly systemLogs: SystemLogsApi;
    readonly subscribers: SubscribersApi;
    readonly taxClasses: TaxClassesApi;
    readonly taxRatesAndZones: TaxRatesAndZonesApi;
    readonly taxProperties: TaxPropertiesApi;
    readonly taxSettings: TaxSettingsApi;
    readonly wishlists: WishlistsApi;
    readonly paymentMethods: PaymentMethodsApi;
    readonly paymentProcessing: PaymentProcessingApi;
    readonly abandonedCartEmails: AbandonedCartEmailsApi;
    readonly customTemplateAssociations: CustomTemplateAssociationsApi;
    readonly emailTemplates: EmailTemplatesApi;
    readonly pages: PagesApi;
    readonly marketing: MarketingApi;
    readonly storeContent: StoreContentApi;
    readonly themes: ThemesApi;
    readonly widgets: WidgetsApi;
    readonly taxProviderConnection: TaxProviderConnectionApi;
    readonly webhooks: WebhooksApi;
    constructor(config: Config);
    getResources<T>(resourceUrl: string, page?: number, limit?: number): Promise<T[]>;
    enableCache(enable: boolean, ttl?: number): void;
    flushCache(region?: string): Promise<void>;
}
