import { ApiClient } from "../api-client";
import { CatalogSettingsApi } from "./catalog-settings-api";
import { AnalyticsSettingsApi } from "./analytics-settings-api";
import { EmailSettingsApi } from "./email-settings-api";
import { FaviconImageSettingsApi } from "./favicon-image-settings-api";
import { InventorySettingsApi } from "./inventory-settings-api";
import { InventoryNotificationSettingsApi } from "./inventory-notification-settings-api";
import { LogoSettingsApi } from "./logo-settings-api";
import { LogoImageSettingsApi } from "./logo-image-settings-api";
import { SearchFilterSettingsApi } from "./search-filter-settings-api";
import { StoreLocaleSettingsApi } from "./store-locale-settings-api";
import { StoreProfileSettingsApi } from "./store-profile-settings-api";
import { StorefrontProductSettingsApi } from "./storefront-product-settings-api";
import { StorefrontRobotsTxtSettingsApi } from "./storefront-robots-txt-settings-api";
import { StorefrontSearchSettingsApi } from "./storefront-search-settings-api";
import { StorefrontSecuritySettingsApi } from "./storefront-security-settings-api";
import { StorefrontSeoSettingsApi } from "./storefront-seo-settings-api";
import { StorefrontStatusSettingsApi } from "./storefront-status-settings-api";
export declare class SettingsApi {
    private readonly apiClient;
    constructor(apiClient: ApiClient);
    readonly analytics: AnalyticsSettingsApi;
    readonly catalogs: CatalogSettingsApi;
    readonly emailStatuses: EmailSettingsApi;
    readonly faviconImage: FaviconImageSettingsApi;
    readonly inventory: InventorySettingsApi;
    readonly inventoryNotifications: InventoryNotificationSettingsApi;
    readonly logo: LogoSettingsApi;
    readonly logoImage: LogoImageSettingsApi;
    readonly searchFilters: SearchFilterSettingsApi;
    readonly storeLocale: StoreLocaleSettingsApi;
    readonly storeProfile: StoreProfileSettingsApi;
    readonly storefrontProduct: StorefrontProductSettingsApi;
    readonly storefrontRobotsTxt: StorefrontRobotsTxtSettingsApi;
    readonly storefrontSearch: StorefrontSearchSettingsApi;
    readonly storefrontSecurity: StorefrontSecuritySettingsApi;
    readonly storefrontSeo: StorefrontSeoSettingsApi;
    readonly storefrontStatus: StorefrontStatusSettingsApi;
}
